<?php
$_product = $this->getProduct();
$instockDate = $_product->getInstockDate();
?>
<?php if ($instockDate): ?>
    <div class="product-instock-date">
        <strong><?php echo $this->__('Instock Date:') ?></strong>
        <?php echo $instockDate; ?>
    </div>
<?php else: ?>
    <div class="product-instock-date">
        <strong><?php echo $this->__('Instock Date:') ?></strong>
        <?php echo $this->__('No Date'); ?>
    </div>
<?php endif; ?>

<div class="product-brand">
    <strong><?php echo $this->__('Brand:') ?></strong>
    <?php echo ($_product->getAttributeText('brand')) ? $_product->getAttributeText('brand') : $this->__('No Brand'); ?>
</div>
<div class="product-islocationcheck">
    <strong><?php echo $this->__('Is Location Check:') ?></strong>
    <?php echo ($_product->getAttributeText('is_exclude_location_check')) ? $_product->getAttributeText('is_exclude_location_check') : $this->__('No is_exclude_location_check'); ?>
</div>
