<?php
$_product = $this->getProduct();
$instockDate = $_product->getInstockDate();
?>
<?php if ($instockDate): ?>
    <div class="product-instock-date">
        <strong><?php echo $this->__('Instock Date:') ?></strong>
        <?php echo $instockDate; ?>
    </div>
<?php else: ?>
    <div class="product-instock-date">
        <strong><?php echo $this->__('Instock Date:') ?></strong>
        <?php echo $this->__('No Date'); ?>
    </div>
<?php endif; ?>

<div class="product-brand">
    <strong><?php echo $this->__('Brand:') ?></strong>
    <?php echo ($_product->getAttributeText('brand')) ? $_product->getAttributeText('brand') : $this->__('No Brand'); ?>
</div>

<div class="product-soldcount">
    <strong><?php echo $this->__('Sold Count:') ?></strong>
    <?php echo ($_product->getSoldCount()) ? $_product->getData('sold_count') : $this->__('No Sold Count'); ?>
</div>

