<div id="configuration-container">
    <div id="main_container" width="200px" height="200px" style="border:1px solid black">
        <button id="add_new_table_btn">Add New Table</button>
        <button id="save_configuration_btn">Save Configuration</button>
    </div>
</div>

<script>
    document.observe('dom:loaded', function () {
        var config = new Configuration({
            // containerId: 'sub_div_btn',
            redirected_url: '<?php echo $this->getUrl('*/*/saveConfigurationEvent') ?>',
            loadUrl: '<?php echo $this->getUrl('*/*/load') ?>',
            form_key: FORM_KEY
        });
    });
</script>
