<?php
$url = $this->getUrl('*/*/save');
?>
    <table id="dynamicTable" data-url="<?php echo $url; ?>">
        <tr>
            <td rowspan="1">
                <div>
                    <textarea></textarea>
                    <button class="add-reply">Add Reply</button>
                    <button class="complete">Complete</button>
                </div>
            </td>
        </tr>
    </table>
  

