<?php
echo get_class($this);
$ticketCollection = $this->getTicketCollection();
?>
<?php echo $this->getChildHtml('ticketsystem.filter'); ?>

<table border="1" cellspacing="0" cellpadding="5">
    <thead>
        <tr>
            <th>Ticket ID</th>
            <th>Title</th>
            <th>Description</th>
            <th>Status</th>
            <th>Created At</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($ticketCollection as $ticket):
            // print_r($ticket->getStatus());
            $statusModel = $this->getStatus($ticket->getStatus());
            // $statusColor = $this->getStatusColor($ticket->getStatus());
        
            ?>
            <tr>
                <td><?php echo $ticket->getTicketId(); ?></td>
                <td><?php echo $ticket->getTitle(); ?></td>
                <td><?php echo htmlspecialchars_decode($ticket->getDescription()); ?></td>
                <td bgcolor="<?php echo $statusModel->getColorCode(); ?>"><?php echo $statusModel->getLabel(); ?></td>

                <!-- <td bgcolor="<?php //echo $statusColor ?>"><?php //echo $ticket->getStatus(); ?></td> -->
                <td><?php echo $ticket->getCreatedAt(); ?></td>
                <td><a
                        href="<?php echo $this->getUrl('*/ticketsystem/view', array('id' => $ticket->getTicketId())); ?>">View</a>
                </td>
                <!-- <td><button onclick="viewTicket('<?php //echo $ticket->getTicketId(); ?>')">View</button></td> -->
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>


<div class="pagination">
    <?php echo $this->getPaginationHtml(); ?>
</div>


