<button class="add-filter-button">Add Filter</button>
<?php echo $this->getChildHtml('ticketsystem.filter.button'); ?>


<div class="popup-container" style="display: none;">
    <form class="filter-form">
        <div>
            <label for="status">Status:</label>
            <select name="status" multiple>
                <?php foreach ($this->getStatusOptions() as $id => $label): ?>
                    <option value="<?php echo $id; ?>"><?php echo $label; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div>
            <label for="assign_to">Assign To:</label>
            <select name="assign_to" multiple>
                <?php foreach ($this->getUsers() as $userId => $username): ?>
                    <?php $selected = ($userId == $this->getCurrentUserId()) ? 'selected' : ''; ?>
                    <option value="<?php echo $userId; ?>" <?php echo $selected; ?>><?php echo $username; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div>
            <label for="created_date">Created Date:</label>
            <input type="text" name="created_date" />
        </div>
        <div>
            <label for="user_comment">User Comment:</label>
            <select name="user_comment">
                <?php foreach ($this->getUsers() as $userId => $username): ?>
                    <?php $selected = ($userId == $this->getCurrentUserId()) ? 'selected' : ''; ?>
                    <option value="<?php echo $userId; ?>" <?php echo $selected; ?>><?php echo $username; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div>
            <label for="label">Label:</label>
            <input type="text" name="label" />
        </div>
        <div>
            <button type="button" class="save-button">Save</button>
            <button type="button" class="close-popup-button">Cancel</button>
        </div>
    </form>
</div>

<div class="filter-buttons-container"></div>
<script type="text/javascript">
    document.observe('dom:loaded', function () {
        var custom_filter = new customFilter(
            '<?php echo $this->getUrl('*/*/saveFilter') ?>',
            FORM_KEY,
        );
    });
</script>