<?php

$ticketCollection = $this->getTicketCollection();
?>

<table border="1" cellspacing="0" cellpadding="5">
    <thead>
        <tr>
            <th>Ticket ID</th>
            <th>Title</th>
            <th>Description</th>
            <th>Status</th>
            <th>Created At</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($ticketCollection as $ticket): 
            $statusColor = $this->getStatusColor($ticket->getStatusId());?>
        
            <tr>
                <td><?php echo $ticket->getTicketId(); ?></td>
                <td><?php echo $ticket->getTitle(); ?></td>
                <td><?php echo htmlspecialchars_decode($ticket->getDescription()); ?></td>
                <td bgcolor="<? $statusColor ?>"><?php echo $ticket->getStatusId(); ?></td>
                <td><?php echo $ticket->getCreatedAt(); ?></td>
                <td><a href="<?php echo $this->getUrl('*/ticketsystem/view', array('id' => $ticket->getTicketId())); ?>">View</a></td>
                <!-- <td><button onclick="viewTicket('<?php //echo $ticket->getTicketId(); ?>')">View</button></td> -->
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>


