<div class="comments-section">
   <!-- Click To add Comments → <button id="add-comment-btn">Add Comment</button> -->
    <br>
    <div id="comment-form-container" style="display: none;">
        <form id="comment-form" method="post" data-url="<?php echo $this->getUrl('*/*/addComment') ?>">
            <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <input name="userid" type="hidden" value="<?php echo Mage::getSingleton('admin/session')->getUser()->getId() ?>" />
            <input type="hidden" name="ticketid" value="<?php echo $this->getRequest()->getParam('id') ?>" />
            <label for="comment-title">Title</label>
            <input type="text" id="comment-title" name="title" required><br>

            <label for="comment-description">Description</label>
            <textarea id="comment-description" name="description" class="editor"></textarea><br>

            <button type="button" id="submit-comment">Submit</button>
        </form>
    </div>

    <br>


<script src="https://cdn.ckeditor.com/4.16.2/standard/ckeditor.js"></script>

<div id="comment_replay">
    <?php echo $this->getChildHtml('ticketsystem.view.comment.reply'); ?>
</div>