<?php
foreach ($this->getButtons() as $button) { ?>
    <button name="<?php echo $button ?>" onclick="applyFilterInstance.addFilter(this)"><?php echo $button ?></button>
<?php } ?>
<script type="text/javascript">
    document.observe('dom:loaded', function () {
        var applyFilterInstance = new applyFilter(
            '<?php echo $this->getUrl('*/*/applyFilter') ?>',
            FORM_KEY,
        );
        window.applyFilterInstance = applyFilterInstance;
    });
</script>